name: Deploy Gatsby site to GitHub Pages

on:
  push:
    branches:
      - main  # Запускать действия при пуше в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Gatsby site
        run: npm run build --prefix-paths

      - name: Deploy Gatsby site
        run: npm run deploy


